import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Layout, Typography } from "antd";
import { routes } from "@/routes/routes";
import Link from "next/link";
import TemplateSteps from "./steps.component";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Layout className="w-screen h-screen">
          <header className="bg-gradient-to-r from-[#002C6A] to-[#0C9FE0] flex items-center">
            <Link href={routes.welcome}>
              <Typography className="text-4xl font-bold text-white p-6">
                TEMPLATE
              </Typography>
            </Link>
          </header>
          <div className="w-full h-full bg-gradient-to-b from-[#E7E7E7] to-[#E7EAEC] flex items-center justify-center">
            <div className="bg-white w-3/6 h-2/3 rounded-xl flex flex-col items-center justify-center">
              <TemplateSteps />
              {children}
            </div>
          </div>
        </Layout>
      </body>
    </html>
  );
}
